#!/bin/bash
#BSUB -J convert_gsm[1-3]%2
#BSUB -o /storage1/fs1/cooper_m/Active/r.sivani/Teaseq/paper_analysis/raw_data/mlin/gse266524/fastq2/logs/convert_%I.out
#BSUB -e /storage1/fs1/cooper_m/Active/r.sivani/Teaseq/paper_analysis/raw_data/mlin/gse266524/fastq2/logs/convert_%I.err
#BSUB -n 1
#BSUB -M 16000
#BSUB -W 12:00

set -e
set -o pipefail

source ~/.bashrc
conda activate teaseq

BASE_DIR="/storage1/fs1/cooper_m/Active/r.sivani/Teaseq/paper_analysis/raw_data/mlin/gse266524"
GSM=$(sed -n "${LSB_JOBINDEX}p" /storage1/fs1/cooper_m/Active/r.sivani/Teaseq/paper_analysis/raw_data/mlin/gse266524/gsm_list.txt)
echo "Processing GSM: ${GSM}"
SRA_DIR="${BASE_DIR}/sra/${GSM}"
FASTQ_DIR="${BASE_DIR}/fastq2/${GSM}"

mkdir -p ${FASTQ_DIR}

for SRA_FILE in ${SRA_DIR}/*/*.sra

do
     [ -f "${SRA_FILE}" ] || { echo "No .sra files found in ${SRA_DIR}, skipping."; break; }
    fastq-dump \
        --split-files \
        --origfmt \
        --gzip \
        --outdir ${FASTQ_DIR} \
        ${SRA_FILE}
done
